apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: landingpage-backend-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  chartGitPath: landingpage-backend
  releaseName: landingpage-backend-dev
  values:
    image: registry.novaonx.com/novaonx/landingpage-backend:latest
    replicaCount: 1
    hpa:
      enabled: false
