apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: landingpage-backend-rc
  namespace: stg
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  chartGitPath: landingpage-backend
  releaseName: landingpage-backend-rc
  values:
    image: registry.novaonx.com/novaonx/landingpage-backend:latest
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
